### ISSUE TITLE
.png .jpg .gif no longer supported?

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#1349]
`.png` `.jpg` `.gif` badges no longer show up.
Errors thrown in console (same error for each type):
```cmd
[server] 1206212324 svg2img error Error: Stream yields empty buffer
[server]     at Socket.<anonymous> (C:\Users\Dan\Documents\GitHub\shields\node_modules\gm\lib\command.js:57:17)
[server]     at emitNone (events.js:110:20)
[server]     at Socket.emit (events.js:207:7)
[server]     at endReadableNT (_stream_readable.js:1057:12)
[server]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[server]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)\
```

**Comment by paulmelnikow** [comment]
Hmm, still working on staging and in test. Do you have imagemagick installed?

**Comment by RedSparr0w** [comment]
I'm fairly sure i have it installed, must be a problem on my end though!
forgot to test it on the staging server.
