### ISSUE TITLE
Unit test for formatDate() fails if you run it on 1st January

### ISSUE THREAD

**Issue by chris48s** [badges/shields#1412]
```
  1) Text formatters
       formatDate()
         when given the beginning of this year
           should return 'january':
     Error: Test case failed: expected 'january' to equal 'today'
      at TestCaseError (node_modules/sazerac/lib/errors.js:24:10)
      at deepEqual (node_modules/sazerac/lib/deepEqual.js:16:37)
      at testExecuter (node_modules/sazerac/lib/describer.js:68:27)
      at Context.<anonymous> (node_modules/sazerac/lib/describer.js:49:11)
```

I think this is because the test is written in such a way that the test is non-deterministic rather than because `formatDate()` is broken.

**Comment by paulmelnikow** [comment]
Hahaha that's a good one! Happy new year! :)

**Comment by paulmelnikow** [comment]
As written, it'll be broken until February.
