### ISSUE TITLE
can't host my own server

### ISSUE THREAD

**Issue by edmundhei** [badges/shields#1484]
I follow this guide https://github.com/badges/shields/blob/master/doc/self-hosting.md
When I run  `sudo npm install ` i ran in to this error.

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b custom_files git://github.com/patriksimek/vm2.git /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d
npm ERR! /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edmund/.npm/_logs/2018-02-02T17_57_55_029Z-debug.log
```

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 3aae1e915c0ece28
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall gh-badges@1.3.0
7 info lifecycle gh-badges@1.3.0~preinstall: gh-badges@1.3.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for vm2@github:patriksimek/vm2#7e82f90ac705fc44fad044147cb0df09b4c79a57 Command failed: /usr/bin/git clone --depth=1 -q -b custom_files git://github.com/patriksimek/vm2.git /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d
13 silly fetchPackageMetaData /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d/.git: Permission denied
14 silly saveTree gh-badges@1.3.0
14 silly saveTree ├── @mapbox/react-click-to-select@2.1.0
14 silly saveTree ├── almost-equal@1.1.0
14 silly saveTree ├─┬ babel-eslint@8.0.2
14 silly saveTree │ ├─┬ @babel/code-frame@7.0.0-beta.32
14 silly saveTree │ │ └─┬ chalk@2.3.0
14 silly saveTree │ │   ├─┬ ansi-styles@3.2.0
14 silly saveTree │ │   │ └─┬ color-convert@1.9.0
14 silly saveTree │ │   │   └── color-name@1.1.3
14 silly saveTree │ │   └── supports-color@4.5.0
14 silly saveTree │ ├─┬ @babel/traverse@7.0.0-beta.32
14 silly saveTree │ │ ├─┬ @babel/helper-function-name@7.0.0-beta.32
14 silly saveTree │ │ │ ├─┬ @babel/helper-get-function-arity@7.0.0-beta.32
14 silly saveTree │ │ │ │ └─┬ @babel/types@7.0.0-beta.32
14 silly saveTree │ │ │ │   └── to-fast-properties@2.0.0
14 silly saveTree │ │ │ ├─┬ @babel/template@7.0.0-beta.32
14 silly saveTree │ │ │ │ └── babylon@7.0.0-beta.32
14 silly saveTree │ │ │ └── @babel/types@7.0.0-beta.32
14 silly saveTree │ │ ├── @babel/types@7.0.0-beta.32
14 silly saveTree │ │ ├── babylon@7.0.0-beta.32
14 silly saveTree │ │ ├─┬ debug@3.1.0
14 silly saveTree │ │ │ └── ms@2.0.0
14 silly saveTree │ │ └── globals@10.3.0
14 silly saveTree │ ├── @babel/types@7.0.0-beta.32
14 silly saveTree │ └── babylon@7.0.0-beta.32
14 silly saveTree ├─┬ babel-polyfill@6.26.0
14 silly saveTree │ ├─┬ babel-runtime@6.26.0
14 silly saveTree │ │ └── core-js@2.5.1
14 silly saveTree │ ├── core-js@2.5.1
14 silly saveTree │ └── regenerator-runtime@0.10.5
14 silly saveTree ├─┬ babel-preset-env@1.6.1
14 silly saveTree │ ├── babel-plugin-check-es2015-constants@6.22.0
14 silly saveTree │ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
14 silly saveTree │ ├─┬ babel-plugin-transform-async-to-generator@6.24.1
14 silly saveTree │ │ ├─┬ babel-helper-remap-async-to-generator@6.24.1
14 silly saveTree │ │ │ ├─┬ babel-helper-function-name@6.24.1
14 silly saveTree │ │ │ │ ├─┬ babel-helper-get-function-arity@6.24.1
14 silly saveTree │ │ │ │ │ └── babel-types@6.26.0
14 silly saveTree │ │ │ │ ├─┬ babel-template@6.26.0
14 silly saveTree │ │ │ │ │ ├─┬ babel-traverse@6.26.0
14 silly saveTree │ │ │ │ │ │ ├─┬ babel-code-frame@6.26.0
14 silly saveTree │ │ │ │ │ │ │ └─┬ chalk@1.1.3
14 silly saveTree │ │ │ │ │ │ │   └── ansi-styles@2.2.1
14 silly saveTree │ │ │ │ │ │ ├── babel-messages@6.23.0
14 silly saveTree │ │ │ │ │ │ ├── babylon@6.18.0
14 silly saveTree │ │ │ │ │ │ └─┬ debug@2.6.9
14 silly saveTree │ │ │ │ │ │   └── ms@2.0.0
14 silly saveTree │ │ │ │ │ └── babylon@6.18.0
14 silly saveTree │ │ │ │ ├── babel-traverse@6.26.0
14 silly saveTree │ │ │ │ └── babel-types@6.26.0
14 silly saveTree │ │ │ ├── babel-template@6.26.0
14 silly saveTree │ │ │ ├── babel-traverse@6.26.0
14 silly saveTree │ │ │ └── babel-types@6.26.0
14 silly saveTree │ │ └── babel-plugin-syntax-async-functions@6.13.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-block-scoping@6.26.0
14 silly saveTree │ ├─┬ babel-plugin-transform-es2015-classes@6.24.1
14 silly saveTree │ │ ├── babel-helper-define-map@6.26.0
14 silly saveTree │ │ ├── babel-helper-optimise-call-expression@6.24.1
14 silly saveTree │ │ └── babel-helper-replace-supers@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-computed-properties@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-destructuring@6.23.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-for-of@6.23.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-function-name@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-literals@6.22.0
14 silly saveTree │ ├─┬ babel-plugin-transform-es2015-modules-amd@6.24.1
14 silly saveTree │ │ └─┬ babel-plugin-transform-es2015-modules-commonjs@6.26.0
14 silly saveTree │ │   └── babel-plugin-transform-strict-mode@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-modules-commonjs@6.26.0
14 silly saveTree │ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.24.1
14 silly saveTree │ │ └── babel-helper-hoist-variables@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-modules-umd@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-object-super@6.24.1
14 silly saveTree │ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1
14 silly saveTree │ │ └── babel-helper-call-delegate@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1
14 silly saveTree │ ├── babel-plugin-transform-es2015-spread@6.22.0
14 silly saveTree │ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1
14 silly saveTree │ │ └── babel-helper-regex@6.26.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-template-literals@6.22.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
14 silly saveTree │ ├── babel-plugin-transform-es2015-unicode-regex@6.24.1
14 silly saveTree │ ├─┬ babel-plugin-transform-exponentiation-operator@6.24.1
14 silly saveTree │ │ ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
14 silly saveTree │ │ │ └── babel-helper-explode-assignable-expression@6.24.1
14 silly saveTree │ │ └── babel-plugin-syntax-exponentiation-operator@6.13.0
14 silly saveTree │ ├── babel-plugin-transform-regenerator@6.26.0
14 silly saveTree │ └─┬ browserslist@2.5.1
14 silly saveTree │   └── caniuse-lite@1.0.30000748
14 silly saveTree ├─┬ camp@17.2.1
14 silly saveTree │ └── cookies@0.5.1
14 silly saveTree ├── chai-string@1.4.0
14 silly saveTree ├─┬ chai@4.1.2
14 silly saveTree │ ├── assertion-error@1.0.2
14 silly saveTree │ └── check-error@1.0.2
14 silly saveTree ├── chainsmoker@0.1.0
14 silly saveTree ├─┬ check-node-version@3.1.1
14 silly saveTree │ └─┬ chalk@2.3.0
14 silly saveTree │   ├── ansi-styles@3.2.0
14 silly saveTree │   └── supports-color@4.5.0
14 silly saveTree ├─┬ child-process-promise@2.2.1
14 silly saveTree │ └── cross-spawn@4.0.2
14 silly saveTree ├─┬ chrome-web-store-item-property@1.1.2
14 silly saveTree │ ├── array-includes@3.0.3
14 silly saveTree │ ├─┬ cheerio@0.20.0
14 silly saveTree │ │ └─┬ css-select@1.2.0
14 silly saveTree │ │   ├── boolbase@1.0.0
14 silly saveTree │ │   └── css-what@2.1.0
14 silly saveTree │ └─┬ create-error-class@3.0.2
14 silly saveTree │   └── capture-stack-trace@1.0.0
14 silly saveTree ├── classnames@2.2.5
14 silly saveTree ├─┬ concurrently@3.5.1
14 silly saveTree │ ├─┬ chalk@0.5.1
14 silly saveTree │ │ ├── ansi-styles@1.1.0
14 silly saveTree │ │ ├─┬ has-ansi@0.1.0
14 silly saveTree │ │ │ └── ansi-regex@0.2.1
14 silly saveTree │ │ ├── strip-ansi@0.3.0
14 silly saveTree │ │ └── supports-color@0.2.0
14 silly saveTree │ ├── commander@2.6.0
14 silly saveTree │ └─┬ supports-color@3.2.3
14 silly saveTree │   └── has-flag@1.0.0
14 silly saveTree └─┬ danger@3.0.0
14 silly saveTree   ├─┬ chalk@2.3.0
14 silly saveTree   │ ├── ansi-styles@3.2.0
14 silly saveTree   │ └── supports-color@4.5.0
14 silly saveTree   ├── commander@2.12.2
14 silly saveTree   ├─┬ debug@3.1.0
14 silly saveTree   │ └── ms@2.0.0
14 silly saveTree   └── github@13.0.1
15 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b custom_files git://github.com/patriksimek/vm2.git /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d
15 verbose stack /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d/.git: Permission denied
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at maybeClose (internal/child_process.js:925:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
15 verbose stack     at emitOne (events.js:116:13)
15 verbose stack     at Socket.emit (events.js:211:7)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
16 verbose cwd /var/www/html/shields
17 verbose Linux 4.4.0-87-generic
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
19 verbose node v8.9.4
20 verbose npm  v5.6.0
21 error code 1
22 error Command failed: /usr/bin/git clone --depth=1 -q -b custom_files git://github.com/patriksimek/vm2.git /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d
22 error /home/edmund/.npm/_cacache/tmp/git-clone-46678c4d/.git: Permission denied
23 verbose exit [ 1, true ]
```

**Comment by paulmelnikow** [comment]
Try `npm cache clean`?

**Comment by edmundhei** [comment]
I get this error when i execute `sudo node server 8080` 

```
No secret data found at /var/www/html/shields/private/secret.json (see lib/server-secrets.js)
0202213421 Server is starting up: http://[::]:8080/
No fallback font set.
Unable to load fallback font. Using Helvetica-Bold instead.
^Z
[1]+  Stopped                 sudo node server 8080
┌─[✗]─[edmund@Miley]─[/var/www/html/shields]
└──╼ $sudo node server 8080
[sudo] password for edmund:
Sorry, try again.
[sudo] password for edmund:
No secret data found at /var/www/html/shields/private/secret.json (see lib/server-secrets.js)
0202221057 Server is starting up: http://[::]:8080/
No fallback font set.
Unable to load fallback font. Using Helvetica-Bold instead.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Camp.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by paulmelnikow** [comment]
Either the Shields server is already running, or something else is running on that port. Use a different port, or restart.

**Comment by edmundhei** [comment]
Thanks that work. Just one more question, how do i make it auto start? I try using crontab -e but didnt work.

**Comment by paulmelnikow** [comment]
That would depend on your system, and I'm afraid is out of scope of the kind of stuff we can help with here. I'd suggest https://serverfault.com/
