### ISSUE TITLE
Crash in makeBadge/capitalize

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1606]
https://sentry.io/shields/imgshieldsio/issues/505140091/

```
Error: TypeError: Cannot read property 'toUpperCase' of undefined
    at capitalize (/home/m/shields/lib/make-badge.js:82:15)
    at makeBadge (/home/m/shields/lib/make-badge.js:117:15)
    at data (/home/m/shields/lib/make-badge.js:178:40)
    at /home/m/shields/server.js:8026:17
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
  File "/home/m/shields/lib/make-badge.js", line 82, in capitalize
    return s[0].toUpperCase() + s.slice(1);
  File "/home/m/shields/lib/make-badge.js", line 117, in makeBadge
    text[0] = capitalize(text[0]);
  File "/home/m/shields/lib/make-badge.js", line 178, in data
    makeMakeBadgeFn: measurer => data => makeBadge(measurer, data),
  File "/home/m/shields/server.js", line 8026, in null.<anonymous>
    const svg = makeBadge(badgeData);
  File "/home/m/shields/lib/sys/monitor.js", line 46, in Array.monitorHandler
    next();
...
(58 additional frame(s) were not displayed)

Error: TypeError: Cannot read property 'toUpperCase' of undefined
    at capitalize (/home/m/shields/lib/make-badge.js:82:15)
    at makeBadge (/home/m/shields/lib/make-badge.js:117:15)
    at data (/home/m/shields/lib/make-badge.js:178:40)
    at /home/m/shields/server.js:8026:17
    at gotQueries (/home/m/shields/node_modules/camp/lib/camp.js:910:7)
    at getQueries (/home/m/shields/node_modules/camp/lib/camp.js:241:5)
    at catchpath (/home/m/shields/node_modules/camp/lib/camp.js:903:3)
    at Array.routeLayer (/home/m/shields/node_modules/camp/lib/camp.js:865:7)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.pathLayer (/home/m/shields/node_modules/camp/lib/camp.js:838:16)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.eventSourceLayer (/home/m/shields/node_modules/camp/lib/camp.js:617:49)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.ajaxLayer (/home/m/shields/node_modules/camp/lib/camp.js:517:39)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.wsLayer (/home/m/shields/node_modules/camp/lib/camp.js:506:50)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.genericLayer (/home/m/shields/node_modules/camp/lib/camp.js:444:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at next (/home/m/shields/node_modules/camp/lib/camp.js:408:46)
    at Array.monitorHandler (/home/m/shields/lib/sys/monitor.js:46:5)
    at bubble (/home/m/shields/node_modules/camp/lib/camp.js:407:26)
    at listener (/home/m/shields/node_modules/camp/lib/camp.js:401:3)
    at SecureCamp.<anonymous> (/home/m/shields/node_modules/camp/lib/camp.js:364:45)
    at SecureCamp.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

**Comment by PyvesB** [comment]
Related pull request merged, closing.
