### ISSUE TITLE
Crash in addv

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1609]
https://sentry.io/shields/imgshieldsio/issues/503419670/

```
Error: Vendor hook error:,TypeError: Cannot read property 'startsWith' of undefined
    at addv (/home/m/shields/lib/text-formatters.js:71:15)
    at /home/m/shields/server.js:5652:25
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/lib/text-formatters.js", line 71, in addv
    if (version.startsWith('v') || ignoredVersionPatterns.test(version)) {
  File "/home/m/shields/server.js", line 5652, in null.<anonymous>
    badgeData.text[1] = versionText(version);
  File "/home/m/shields/lib/request-handler.js", line 166, in Request.request [as _callback]
    callback(err, res, body);
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
  File "/home/m/shields/lib/request-handler.js", line 32, in Domain.vendorDomain.on.err
    log.error('Vendor hook error:', err.stack);
...
(14 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: Cannot read property 'startsWith' of undefined
    at addv (/home/m/shields/lib/text-formatters.js:71:15)
    at /home/m/shields/server.js:5652:25
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:166:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by PyvesB** [comment]
This is closely related to #1599. I'll take care of it, but I would first like some opinions on #1615 as the fix may be very similar here. 😉
