### ISSUE TITLE
Spurious Travis error

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1611]
https://sentry.io/shields/shields/issues/503517592/

```
Error: Travis error: Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25)
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
  File "/home/m/shields/server.js", line 406, in null.<anonymous>
    log.error('Travis error: ' + err.stack);
  File "/home/m/shields/lib/request-handler.js", line 166, in Request.request [as _callback]
    callback(err, res, body);
...
(9 additional frame(s) were not displayed)

Error: Travis error: Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25)
```

At this point, this error doesn't seem worth logging.

**Comment by paulmelnikow** [comment]
A related but distinct issue:

```
Error: Travis error: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (https.js:245:10)
    at Request.start (/home/m/shields/node_modules/request/request.js:748:32)
    at Request.end (/home/m/shields/node_modules/request/request.js:1512:10)
    at end (/home/m/shields/node_modules/request/request.js:561:14)
    at Immediate._onImmediate (/home/m/shields/node_modules/request/request.js:575:7)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

I think this means that, under some circumstances, we're passing something into the request URL which needs to be sanitized first.
