### ISSUE TITLE
`docker run` fails with dependency error

### ISSUE THREAD

**Issue by philipithomas** [badges/shields#1618]
Running the docker build and docker run on master is giving me this error:

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/server.js:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

I verified on a second machine.

**Comment by philipithomas** [comment]
I believe that the issue is that glob is listed as a dev dependency

**Comment by paulmelnikow** [comment]
Thanks for reporting this, and for the fix!
