### ISSUE TITLE
Crash in makeLabel when queryData is undefined

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1781]
https://sentry.io/shields/shields/issues/518922897/

```
Error: Vendor hook error:,TypeError: Cannot read property 'label' of undefined
    at makeLabel (/home/m/shields/lib/badge-data.js:61:20)
    at variants. (/home/m/shields/server.js:2005:27)
    at /home/m/shields/server.js:2030:7
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:168:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/lib/badge-data.js", line 61, in makeLabel
    return overrides.label || defaultLabel;
  File "/home/m/shields/server.js", line 2005, in variants.
    badgeData.text[0] = getLabel(`conda|${badgeData.text[0]}`, queryData);
  File "/home/m/shields/server.js", line 2030, in null.<anonymous>
    variant(data, badgeData);
  File "/home/m/shields/lib/request-handler.js", line 168, in Request.request [as _callback]
    callback(err, res, body);
  File "/home/m/shields/lib/log.js", line 36, in Function.error
    Raven.captureException(msg, function (sendErr) {
...
(15 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: Cannot read property 'label' of undefined
    at makeLabel (/home/m/shields/lib/badge-data.js:61:20)
    at variants. (/home/m/shields/server.js:2005:27)
    at /home/m/shields/server.js:2030:7
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:168:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

https://github.com/badges/shields/blob/57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf/server.js#L2005

https://github.com/badges/shields/blob/57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf/lib/badge-data.js#L61

Not sure whether or not this is specific to the conda badge.

**Comment by paulmelnikow** [comment]
This line in the conda badge is in the stack trace, and I believe it is the problem. In the `catch` block we pass `data` to the `variant` in place of `queryData`: https://github.com/badges/shields/blob/57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf/server.js#L2030
