### ISSUE TITLE
NPMLicense color tests failing

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2348]
I expect this failure in NpmLicense is due to #2196:

```
  23) NpmLicense
       license for package with a license array
         
	[ GET /package-license-array.json?style=_shields_test ]:

      AssertionError: expected { Object (colorB, name, ...) } to deeply equal { Object (name, value, ...) }
      + expected - actual

       {
      -  "colorB": "#97CA00"
      +  "colorB": "#9f9f9f"
         "name": "license"
         "value": "MPL-2.0, MIT"
       }
      
      at Object.pathMatch.matchJSON (node_modules/icedfrisby/lib/pathMatch.js:138:38)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:583:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

Ref: #1359

**Comment by chris48s** [comment]
closed in #2401
