### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by BlauerPulli** [badges/shields#2376]
Are you experiencing an issue with...
 - [ ] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

While building the Docker image, at the "npm install" -step several dependencies not installed beacause of missing peer dependencies. (gh-badges installed manually before..) Here the logs:

npm WARN lifecycle shields.io@0.0.0~postinstall: cannot run in wd shields.io@0.0.0 npm run depcheck (wd=/usr/src/app)
npm WARN icedfrisby-nock@1.0.0 requires a peer of icedfrisby@>= 1.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-dynamic-import@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx-source@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-runtime@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/preset-react@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-jsx@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-display-name@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx-self@7.0.0-beta.42 requires a peer of @babel/core@7.0.0-beta.42 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

I installed some peer dependencies before the npm install command but that changes nothing.. dependency. By the used Base Image node is version 8.9.4 and npm (updated) on 6.4.1
:bulb: **Possible Solution**

**Comment by paulmelnikow** [comment]
Hi! Thanks for asking about this.

Those are all warnings. The image should be fine. Are you having problems with it?

**Comment by BlauerPulli** [comment]
Thanks for your answer! Starting the container returns:

raven@2.6.4 alert: no DSN provided, error reporting disabled
Error: Cannot find module 'svgo'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/gh-badges/lib/make-badge.js:5:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/server.js:23:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Yes that are "just" warnings but all the listed packages will be not installed.. and i dont think they are just for fun in the dependency list.

**Comment by paulmelnikow** [comment]
Ahh gotcha. Yea, that’s a problem.

It’s not related to those warnings though. I believe all those packages are installed, but not the versions some other package package wants. They are also build dependencies, and the error you’re seeing is a runtime failure in the server.

**Comment by BlauerPulli** [comment]
to fix it just adapt the Dockerfile like this:

FROM node:8.9.4-alpine

RUN apk add --no-cache gettext imagemagick librsvg git

RUN mkdir -p /usr/src/app
RUN mkdir /usr/src/app/private
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY . /usr/src/app
RUN npm install
RUN npm run build
RUN npm prune --production
RUN npm cache clean --force

CMD envsubst < secret.tpl.json > ./private/secret.json \
 && node server

EXPOSE 80

**Comment by paulmelnikow** [comment]
Thanks! Gonna leave this open until the Dockerfile gets fixed.

It would be nice to get an automated tests around the Docker setup. I'm sure it's kind of annoying for folks that it breaks from time to time.

**Comment by paulmelnikow** [comment]
@calebcartwright Would you be up for tracking down this issue?

**Comment by calebcartwright** [comment]
@paulmelnikow yeah I'll give it a whirl

**Comment by calebcartwright** [comment]
I think we can probably close this now. I can't reproduce this anymore, and guessing that https://github.com/badges/shields/pull/2815 would've fixed this since `svgo` is a dependency of `gh-badges` 

I think #2876 is a better place to track the server start errors in Docker land
