### ISSUE TITLE
make-badge.js causing crash

### ISSUE THREAD

**Issue by stclairdaniel** [badges/shields#2415]
Are you experiencing an issue with...
 - [ ] [shields.io](https://shields.io/#/)
 - [ ] My own instance
 - [x] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
```
node_modules/gh-badges/lib/make-badge.js:14
templateFiles.forEach(async filename => {
                      ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/gh-badges/lib/index.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Using 2.1.0. I have a Gulp task running in Jenkins that does something like:
```
const { BadgeFactory } = require("gh-badges");
const bf = new BadgeFactory();
const format = {
        text: ["storybook", "up to date"],
        colorscheme: "orange",
        template: "flat"
      };
      const svg = bf.create(format);
      fs.writeFileSync(folder + outputFile, svg);
      console.log("Storybook badge generated");
```

but it fails with the above error. Strangely enough, I use this same Gulp task in another project and it doesn't fail here. Any advice or suggestions?

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

That error points to an incompatible Node version. gh-badge v2 requires Node 8+.

**Comment by stclairdaniel** [comment]
Thank you so much - this exactly explains why one project was building and the other wasn't. I really appreciate the quick reply!
