### ISSUE TITLE
Sourcegraph badges return '?'

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2481]
Tests are failing:

```
  7) Sourcegraph
       project usage count
         
	[ GET /rrc/github.com/theupdateframework/notary.json ]:
     ValidationError: child "value" fails because ["value" with value "?" fails to match the required pattern: /^[0-9]*(\.[0-9]k)?\sprojects$/]
      at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
      at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickDomainCallback (internal/process/next_tick.js:219:9)

  8) Sourcegraph
       project without any available information
         
	[ GET /rrc/github.com/PyvesB/EmptyRepo.json ]:

      AssertionError: expected { name: 'used by', value: '?' } to deeply equal { name: 'used by', value: 'invalid' }
      + expected - actual

       {
         "name": "used by"
      -  "value": "?"
      +  "value": "invalid"
       }
      
      at Object.pathMatch.matchJSON (node_modules/icedfrisby/lib/pathMatch.js:138:38)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:583:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

The example badges are also rendering with **?**.

They seem to have [a new GraphQL API](https://docs.sourcegraph.com/api/graphql). I wonder if the old one has been deprecated.

**Comment by calebcartwright** [comment]
Potentially relevant/related: 

* https://about.sourcegraph.com/blog/see-how-many-people-use-your-library-with-sourcegraph-badges
* [sourcegraph/sourcegraph/#145](https://github.com/sourcegraph/sourcegraph/issues/145)
