### ISSUE TITLE
npm start errors out on Windows 10

### ISSUE THREAD

**Issue by Prouser123** [badges/shields#2580]
Are you experiencing an issue with...
 - [ ] [shields.io](https://shields.io/#/)
 - [x] My own instance
 - [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Windows 10 Home 1803, Node.js v8.12.0 (x64)

Similar to #1259, (`ELIFECYCLE` error) but arguments have since changed.

Also tried merging in #1260 but this didn't help the issue.

When running `npm start`, this is the output:
```
> shields.io@0.0.0 start C:\Users\cahil\Documents\GitHub\# - Forks\shields
> concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev"

[server] 'ALLOWED_ORIGIN' is not recognized as an internal or external command,
[server] operable program or batch file.
[frontend] 'BASE_URL' is not recognized as an internal or external command,
[frontend] operable program or batch file.
[server] ALLOWED_ORIGIN=http://localhost:3000 npm run start:server exited with code 1
[frontend] BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shields.io@0.0.0 start: `concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shields.io@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Log file verbose:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle shields.io@0.0.0~prestart: shields.io@0.0.0
6 verbose lifecycle shields.io@0.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle shields.io@0.0.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\cahil\Documents\GitHub\# - Forks\shields\node_modules\.bin;C:\Users\cahil\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\cahil\AppData\Local\Microsoft\WindowsApps;C:\Users\cahil\AppData\Local\GitHubDesktop\bin;C:\Users\cahil\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\cahil\AppData\Roaming\npm;C:\Users\cahil\AppData\Local\now-cli
8 verbose lifecycle shields.io@0.0.0~prestart: CWD: C:\Users\cahil\Documents\GitHub\# - Forks\shields
9 silly lifecycle shields.io@0.0.0~prestart: Args: [ '/d /s /c',
9 silly lifecycle   'npm run depcheck && npm run defs && npm run features' ]
10 silly lifecycle shields.io@0.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle shields.io@0.0.0~start: shields.io@0.0.0
12 verbose lifecycle shields.io@0.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle shields.io@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\cahil\Documents\GitHub\# - Forks\shields\node_modules\.bin;C:\Users\cahil\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\cahil\AppData\Local\Microsoft\WindowsApps;C:\Users\cahil\AppData\Local\GitHubDesktop\bin;C:\Users\cahil\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\cahil\AppData\Roaming\npm;C:\Users\cahil\AppData\Local\now-cli
14 verbose lifecycle shields.io@0.0.0~start: CWD: C:\Users\cahil\Documents\GitHub\# - Forks\shields
15 silly lifecycle shields.io@0.0.0~start: Args: [ '/d /s /c',
15 silly lifecycle   'concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev"' ]
16 silly lifecycle shields.io@0.0.0~start: Returned: code: 1  signal: null
17 info lifecycle shields.io@0.0.0~start: Failed to exec start script
18 verbose stack Error: shields.io@0.0.0 start: `concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:915:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid shields.io@0.0.0
20 verbose cwd C:\Users\cahil\Documents\GitHub\# - Forks\shields
21 verbose Windows_NT 10.0.17134
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 verbose node v8.12.0
24 verbose npm  v6.4.1
25 error code ELIFECYCLE
26 error errno 1
27 error shields.io@0.0.0 start: `concurrently --names server,frontend "ALLOWED_ORIGIN=http://localhost:3000 npm run start:server" "BASE_URL=http://[::]:8080 BABEL_ENV=dev-prod next dev"`
27 error Exit status 1
28 error Failed at the shields.io@0.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```
:bulb: **Possible Solution**

Maybe something like #1270?

**Comment by calebcartwright** [comment]
@Prouser123 - Do you need to deploy your own shields instance on a Windows machine, or were you just trying to work with the codebase locally on your PC? 

When I work on the Shields codebase on my Windows machine I use the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) which you could consider as a temporary solution if your targeting the latter use  case

**Comment by paulmelnikow** [comment]
Ah, this is because you can’t just put env var assignment on the command line in Windows. The cross-env package is the classic solution, which I guess we’ve not yet adopted here.

**Comment by Prouser123** [comment]
> @Prouser123 - Do you need to deploy your own shields instance on a Windows machine, or were you just trying to work with the codebase locally on your PC?
> 
> When I work on the Shields codebase on my Windows machine I use the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) which you could consider as a temporary solution if you're targeting the latter use case

@calebcartwright just trying to work on the codebase. I have an Ubuntu Server I can deploy on if I needed to.

**Comment by paulmelnikow** [comment]
If there aren't other thoughts, we could merge @Prouser123's setup (#2589).

**Comment by PyvesB** [comment]
@chris48s on my side I do things manually by applying a regex that replaces all `VAR=value` occurrences in _package.json_ with `SET VAR=value &&`. Admittedly not great. 😉

**Comment by chris48s** [comment]
> If there aren't other thoughts, we could merge @Prouser123's setup

:+1: Just wanted to check first that we aren't taking on another dependency if we already have a solution to this. Seems like we probably don't
