### ISSUE TITLE
Crash in modified GitHub auth

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2728]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

Post deploy of #1205:

```
Error: Vendor hook error:,Error: usesRemaining must be an integer
    at Token.update (/home/m/shields/lib/token-pool.js:65:13)
    at GithubApiProvider.updateToken (/home/m/shields/services/github/github-api-provider.js:57:11)
    at request (/home/m/shields/services/github/github-api-provider.js:109:16)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:182:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by calebcartwright** [comment]
I don't suppose that the `addToken(tokenString)` function in github-api-provider is actually taking in a string is it?

**Comment by paulmelnikow** [comment]
Still happening after deploy of #2730.

**Comment by paulmelnikow** [comment]
I was suspicious of that too. Though they didn't start appearing until the deploy, and the line numbers seem to correspond. I am seeing this in the Sentry UI, though, and I'm not sure what it means:

<img width="549" alt="screen shot 2019-01-11 at 1 30 34 pm" src="https://user-images.githubusercontent.com/1487036/51052585-1ce3f780-15a5-11e9-8071-a59b206f8829.png">

**Comment by paulmelnikow** [comment]
Sentry issue: [SHIELDS-22](https://sentry.io/shields/shields/issues/841561239/?referrer=github_plugin)

**Comment by calebcartwright** [comment]
That link took me into a sentry sign up page so I'm guessing that in addition to me not having a sentry account that I probably don't have access either?

**Comment by paulmelnikow** [comment]
Right. I think more of the maintainers should have access, though. It's more than I should carry on my own.

**Comment by paulmelnikow** [comment]
Okay, #2736 is the fix. The problem is the badges that use search quota. `rateLimit` for those is 25, and 0.25 times that is, indeed, not an integer.

**Comment by calebcartwright** [comment]
Good find!

**Comment by paulmelnikow** [comment]
Think this is fixed! No new errors in the last minute or so. The search badge is working, too, though I didn't actually try it pre-deploy.
