### ISSUE TITLE
Package Control badges not working

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2747]
:clock11: **When did the problem start?**

In the last day or so.

:camera: **Live badge**

https://img.shields.io/packagecontrol/dm/GitGutter.svg
![](https://img.shields.io/packagecontrol/dm/GitGutter.svg)

:wrench: **Is the live badge working?**

Nope!

:link: **CircleCI link**

https://circleci.com/gh/badges/daily-tests/80

:beetle: **Stack trace**

```
Package Control daily downloads [ GET /dd/GitGutter.json ] - [ GET /dd/GitGutter.json ]
/home/circleci/project/shields/lib/service-test-runner/cli.js
ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /^[1-9][0-9]*[kMGTPEZY]?\/(year|month|4 weeks|week|day)$/]
    at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
    at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
    at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
    at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
    at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
    at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Package Control monthly downloads [ GET /dm/GitGutter.json ] - [ GET /dm/GitGutter.json ]
/home/circleci/project/shields/lib/service-test-runner/cli.js
ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /^[1-9][0-9]*[kMGTPEZY]?\/(year|month|4 weeks|week|day)$/]
    at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
    at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
    at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
    at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
    at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
    at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Package Control total downloads [ GET /dt/GitGutter.json ] - [ GET /dt/GitGutter.json ]
/home/circleci/project/shields/lib/service-test-runner/cli.js
ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /^[1-9][0-9]*[kMGTPEZY]?$/]
    at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
    at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
    at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
    at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
    at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
    at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Package Control weekly downloads [ GET /dw/GitGutter.json ] - [ GET /dw/GitGutter.json ]
/home/circleci/project/shields/lib/service-test-runner/cli.js
ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /^[1-9][0-9]*[kMGTPEZY]?\/(year|month|4 weeks|week|day)$/]
    at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
    at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
    at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
    at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
    at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
    at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
    at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by chris48s** [comment]
This appears to be working.

Maybe the elves fixed it? :sparkles:
