### ISSUE TITLE
Error: Vendor hook error:,TypeError: s.toLowerCase is not a function

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2778]
https://sentry.io/shields/shields/issues/846279983/?referrer=github_plugin

```
Error: Vendor hook error:,TypeError: s.toLowerCase is not a function
    at isHexColor (/home/m/shields/gh-badges/lib/color.js:24:31)
    at normalizeColor (/home/m/shields/gh-badges/lib/color.js:32:14)
    at makeBadge (/home/m/shields/gh-badges/lib/make-badge.js:168:12)
    at sendBadge (/home/m/shields/lib/request-handler.js:283:25)
    at githubApiProvider.request (/home/m/shields/services/github/github-languages.service.js:138:13)
    at request (/home/m/shields/services/github/github-api-provider.js:144:7)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:216:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  File "/home/m/shields/gh-badges/lib/color.js", line 24, in isHexColor
    return hexColorRegex.test(s.toLowerCase())
  File "/home/m/shields/gh-badges/lib/color.js", line 32, in normalizeColor
    } else if (isHexColor(color)) {
  File "/home/m/shields/gh-badges/lib/make-badge.js", line 168, in makeBadge
    color: normalizeColor(color),
  File "/home/m/shields/lib/request-handler.js", line 283, in sendBadge
    const svg = makeBadge(badgeData)
  File "/home/m/shields/services/github/github-languages.service.js", line 138, in githubApiProvider.request
    sendBadge(format, badgeData)
...
(18 additional frame(s) were not displayed)

Error: Vendor hook error:,TypeError: s.toLowerCase is not a function
    at isHexColor (/home/m/shields/gh-badges/lib/color.js:24:31)
    at normalizeColor (/home/m/shields/gh-badges/lib/color.js:32:14)
    at makeBadge (/home/m/shields/gh-badges/lib/make-badge.js:168:12)
    at sendBadge (/home/m/shields/lib/request-handler.js:283:25)
    at githubApiProvider.request (/home/m/shields/services/github/github-languages.service.js:138:13)
    at request (/home/m/shields/services/github/github-api-provider.js:144:7)
    at Request.request [as _callback] (/home/m/shields/lib/request-handler.js:216:9)
    at Request.self.callback (/home/m/shields/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/m/shields/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/m/shields/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by paulmelnikow** [comment]
Seems certainly related to #2742.

**Comment by paulmelnikow** [comment]
The deployed commit is 4597d77015d7e10e758d1c8f4d0894e40bcefdf9.

**Comment by calebcartwright** [comment]
Any chance that's also why the server tests are failing in the daily build?

**Comment by paulmelnikow** [comment]
No, I think this one is in that GitHub badge mentioned in the stack trace. It's only happened three times in the last couple hours; seems pretty isolated.

**Comment by calebcartwright** [comment]
Also I had already started  down the debug path 😄 

At first glance it looks like for `top` there's no colorscheme being set https://github.com/badges/shields/blob/master/services/github/github-languages.service.js#L138

**Comment by paulmelnikow** [comment]
Huh. That's a good point. I wouldn't think not setting a color would break anything… I wonder if it does. It's a logical explanation.

Another possibility is that scoutcamp is turning the query param into null or an array or something and that's triggering it.

Okay. I need to get some rest. Let me know if you figure it out and/or start on the rewrite!

**Comment by paulmelnikow** [comment]
The `makeBadgeData` function would be the place to look for that, btw.

**Comment by calebcartwright** [comment]
Yeah, looks like `makeBadgeData` is still using `colorscheme`, `colorA`, and `colorB`. Maybe we could try setting `color` and `labelColor` to the respective overrides?

**Comment by calebcartwright** [comment]
Or perhaps one of those values is getting set as a number somewhere around [here](https://github.com/badges/shields/blob/master/gh-badges/lib/make-badge.js#L155). 
 
  ¯\_(ツ)_/¯  

I'll need to look at it with fresh eyes tomorrow

**Comment by paulmelnikow** [comment]
https://s0.shields-server.com/badge/foo-bar-blue.svg?colorB=ccc <- works
https://s0.shields-server.com/badge/foo-bar-blue.svg?colorB=012 <- works
https://s0.shields-server.com/badge/foo-bar-blue.svg?colorB=123 <- hangs

https://s0.shields-server.com/github/languages/top/badges/shields.svg?colorB=blue <- works
https://s0.shields-server.com/github/languages/top/badges/shields.svg?colorB=990011 <- hangs

So I think the issue is with Scoutcamp's automatic conversion of query params to numbers. Probably it's not related to the specific badge.

**Comment by paulmelnikow** [comment]
PR opened: #2780.
