### ISSUE TITLE
`npm run test:entrypoint` fails

### ISSUE THREAD

**Issue by platan** [badges/shields#3365]
An interesting part of a log of `npm run test:entrypoint`:
```
Configuration:
{ bind: { address: '--no-config', port: 1111 },
...
[1] "address" must be a valid ip address with a optional CIDR
[2] "address" must be a valid hostname
      at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
      at module.exports.internals.Any.root.attempt (node_modules/joi/lib/index.js:177:29)
      at new Server (core/server/server.js:116:30)
```
<details>
<summary>full log</summary>

```
> shields.io@0.0.0 test:entrypoint /home/m/workspaces/github/shields-platan
> cross-env NODE_CONFIG_ENV=test mocha entrypoint.spec.js



raven@2.6.4 alert: no DSN provided, error reporting disabled
Configuration:
{ bind: { address: '--no-config', port: 1111 },
  metrics: { prometheus: { enabled: false } },
  ssl: { isSecure: false },
  cors: { allowedOrigin: [] },
  persistence: { dir: './private' },
  services: 
   { github: 
      { baseUri: 'https://api.github.com/',
        debug: { enabled: false, intervalSeconds: 200 } },
     trace: false },
  profiling: { makeBadge: false },
  cacheHeaders: { defaultCacheLengthSeconds: 120 },
  rateLimit: false,
  handleInternalErrors: false,
  fetchLimit: '10MB',
  redirectUrl: 'http://badge-server.example.com' }
  1) "before all" hook for "should render a badge"
  2) "after all" hook: shut down the server for "should render a badge"

  0 passing (1s)
  2 failing

  1) "before all" hook for "should render a badge":
     ValidationError: {
  "bind": {
    "port": 1111,
    "address" [1, 2]: "--no-config"
  },
  "metrics": {
    "prometheus": {
      "enabled": false
    }
  },
  "ssl": {
    "isSecure": false
  },
  "cors": {
    "allowedOrigin": []
  },
  "persistence": {
    "dir": "./private"
  },
  "services": {
    "github": {
      "baseUri": "https://api.github.com/",
      "debug": {
        "enabled": false,
        "intervalSeconds": 200
      }
    },
    "trace": false
  },
  "profiling": {
    "makeBadge": false
  },
  "cacheHeaders": {
    "defaultCacheLengthSeconds": 120
  },
  "rateLimit": false,
  "handleInternalErrors": false,
  "fetchLimit": "10MB",
  "redirectUrl": "http://badge-server.example.com"
}

[1] "address" must be a valid ip address with a optional CIDR
[2] "address" must be a valid hostname
      at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
      at module.exports.internals.Any.root.attempt (node_modules/joi/lib/index.js:177:29)
      at new Server (core/server/server.js:116:30)
      at Object.<anonymous> (server.js:25:34)
      at require (internal/module.js:11:18)
      at Context.<anonymous> (entrypoint.spec.js:10:12)

  2) "after all" hook: shut down the server for "should render a badge":
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (entrypoint.spec.js:14:16)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! shields.io@0.0.0 test:entrypoint: `cross-env NODE_CONFIG_ENV=test mocha entrypoint.spec.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the shields.io@0.0.0 test:entrypoint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m/.npm/_logs/2019-04-26T18_39_42_591Z-debug.log
```
</details>

Obviously `--no-config` is not a valid address value. 

Do you have similar results?

`test:entrypoint` was introduced in https://github.com/badges/shields/pull/2613 and it was working properly. 

After fixing this problem task `test:entrypoint` should be added to CI.

My environment: Ubuntu 18.04/Node v8.12.0/npm 6.4.1.

**Comment by paulmelnikow** [comment]
Confirmed. Not sure when that crept in.

The args are coming from mocha:

```
[ '/Users/pnm/.nvm/versions/node/v10.13.0/bin/node',
  '/Users/pnm/code/shields/node_modules/mocha/bin/_mocha',
  'entrypoint.spec.js',
  '--no-config',
  '--no-package',
  '--no-opts',
  '--reporter',
  'mocha-env-reporter',
  '--diff',
  '--extension',
  'js',
  '--slow',
  '75',
  '--timeout',
  '2000',
  '--ui',
  'bdd' ]
```

Setting `process.env = []` in the `before` hook in `entrypoint.spec.js` solves the problem for me. The other alternative would be to run the server in a subprocess. That might be better, though I don't feel strongly one way or another.
