### ISSUE TITLE
Badge request: SDK constraint and dependency version for Dart packages

### ISSUE THREAD

**Issue by cedx** [badges/shields#3471]
The support for [Dart](https://dart.dev) packages is currently pretty basic: we can only get a bagde for the latest version of a package (i.e. `https://img.shields.io/pub/v/<package_name>.svg`).

It exists a specification for the API endpoints exposed by [Pub](https://pub.dev) package manager:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

The API let us access two missing things from `shields.io`:

- the SDK constraint: we can get the Node.js constraint from a npm package, the PHP constraint from a Packagist package, but it's currently impossible with a Dart package.
- the version of a dependency: same here. The badges are available for npm and Packagist packages but not for Pub packages.

It would be very cool if more kind of badges could be generated for Dart projets.

**Comment by PyvesB** [comment]
Hello @cedx !

Thank you for your suggestions! Would you like to contribute to Shields and have a go at implementing these new Dart badges?

Cheers,

Pyves

**Comment by cedx** [comment]
I'm not sure that I'm sufficiently skilled to contribute, but I will try to look at the docs. Currently, I'm having problems with the install (tested on Windows 10 and Ubuntu 19.04 with Node.js 12.2.0):

```
$ npm ci

[...]
Warning: .then() only accepts functions but was passed: [object Object]
    at Installer.updateInstallScript (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:366:8)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:284:18
From previous event:
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:282:10)
From previous event:
    at promiseMap (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:180:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:76:16
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:276:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
    at processImmediate (internal/timers.js:439:21)

Warning: .then() only accepts functions but was passed: [object Object]
    at Installer.updateInstallScript (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:366:8)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:284:18
From previous event:
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:282:10)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
From previous event:
    at LogicalTree.forEachAsync (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:74:33)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:78:22
From previous event:
    at promiseMap (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:180:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:76:16
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:276:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at LogicalTree.forEachAsync (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:74:33)
    at Installer.updateJson (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:272:17)
    at Installer.timedStage (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:79:34)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:89:24
From previous event:
    at Installer.run (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:89:8)
    at EventEmitter.ci (/usr/local/lib/node_modules/npm/lib/ci.js:13:52)
    at Object.commandCache.<computed> (/usr/local/lib/node_modules/npm/lib/npm.js:156:13)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:130:30)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

Warning: .then() only accepts functions but was passed: [object Object]
    at Installer.updateInstallScript (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:366:8)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:284:18
From previous event:
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:282:10)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
From previous event:
    at LogicalTree.forEachAsync (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:74:33)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:78:22
From previous event:
    at promiseMap (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:180:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:76:16
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:276:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
    at processImmediate (internal/timers.js:439:21)

Warning: .then() only accepts functions but was passed: [object Object]
    at Installer.updateInstallScript (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:366:8)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:284:18
From previous event:
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:282:10)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
From previous event:
    at LogicalTree.forEachAsync (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:74:33)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:78:22
From previous event:
    at promiseMap (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:180:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:76:16
    at tree.forEachAsync.concurrency (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:276:14)
    at /usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:75:14
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at LogicalTree.forEachAsync (/usr/local/lib/node_modules/npm/node_modules/npm-logical-tree/index.js:74:33)
    at Installer.updateJson (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:272:17)
    at Installer.timedStage (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:79:34)
    at /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:89:24
From previous event:
    at Installer.run (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:89:8)
    at EventEmitter.ci (/usr/local/lib/node_modules/npm/lib/ci.js:13:52)
    at Object.commandCache.<computed> (/usr/local/lib/node_modules/npm/lib/npm.js:156:13)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:130:30)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

[...]
> jsonpath@1.0.1 postinstall /repo/shields/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


> fast-xml-parser@3.12.16 postinstall /repo/shields/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? You can now support the project on following:
 > https://opencollective.com/fast-xml-parser/donate
 > https://www.patreon.com/bePatron?u=9531404


> styled-components@4.2.0 postinstall /repo/shields/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components

> pose-core@2.1.0 postinstall /repo/shields/node_modules/pose-core
> node ./scripts/postinstall.js || exit 0

      
      +-------------------------------------------------+
      |                                                 |
      |          Hey! Using Pose commercially?          |
      |                                                 |
      |         Pose is completely open source.         |
      |       Its continued development relies on       |
      |          contributions and sponsorship.         |
      |                                                 |
      |          Join us: patreon.com/popmotion         |
      |                                                 |
      +-------------------------------------------------+
      

> fsevents@1.2.8 install /repo/shields/node_modules/fsevents
> node install

internal/modules/esm/default_resolve.js:69
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/repo/shields/node_modules/fsevents/install' imported from /repo/shields/node_modules/fsevents/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:69:13)
    at Loader.resolve (internal/modules/esm/loader.js:70:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:143:40)
    at Loader.import (internal/modules/esm/loader.js:127:28)
    at internal/modules/cjs/loader.js:812:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

> nodemon@1.19.0 postinstall /repo/shields/node_modules/nodemon
> node bin/postinstall || exit 0

internal/modules/esm/default_resolve.js:69
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/repo/shields/node_modules/nodemon/bin/postinstall' imported from /repo/shields/node_modules/nodemon/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:69:13)
    at Loader.resolve (internal/modules/esm/loader.js:70:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:143:40)
    at Loader.import (internal/modules/esm/loader.js:127:28)
    at internal/modules/cjs/loader.js:812:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

> husky@2.3.0 install /repo/shields/node_modules/husky
> node husky install

internal/modules/esm/default_resolve.js:69
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/repo/shields/node_modules/husky/husky' imported from /repo/shields/node_modules/husky/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:69:13)
    at Loader.resolve (internal/modules/esm/loader.js:70:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:143:40)
    at Loader.import (internal/modules/esm/loader.js:127:28)
    at internal/modules/cjs/loader.js:812:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@2.3.0 install: `node husky install`
npm ERR! Exit status 1
```

The trace is VERY long: it exceeds 10000 lines! Some errors are probably related to the fact that I'm using Node.js 12.x.
Installing the package using `npm install --ignore-scripts` works.

**Comment by calebcartwright** [comment]
This should be taken into account as part of #3404

**Comment by cedx** [comment]
My annual summer cleaning of open issues 😄 Closing this one because it's still not resolved after one year... and I don't use Dart anymore, so this is no longer a problem for me.

**Comment by calebcartwright** [comment]
> Closing this one because it's still not resolved after one year... and I don't use Dart anymore, so this is no longer a problem for me

I'm going to reopen this one @cedx. It's not uncommon for feature requests to be outstanding for an extended period of time, especially in a project of Shields' size. Though you may no longer be interested in this one yourself, other Shields users could be and may be sufficiently motivated to implement it! 

Thank you again for the suggestion
