### ISSUE TITLE
Failing GitHub Release Date Service Tests

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3476]
:clock11: **When did the problem start?**
~2 weeks ago (May 8th)

:camera: **Live badge**
The failing tests are currently using `microsoft/vscode` which is returning `no releases or repo not found error`
https://img.shields.io/github/release-date/microsoft/vscode.svg
![](https://img.shields.io/github/release-date/microsoft/vscode.svg)

Other live badges for other repos are working:
https://img.shields.io/github/release-date/SubtitleEdit/SubtitleEdit.svg
![](https://img.shields.io/github/release-date/SubtitleEdit/SubtitleEdit.svg)

![]( url goes here )

:wrench: **Is the live badge working?**
Yes, see above

:link: **CircleCI link**
https://circleci.com/gh/badges/daily-tests/323

:beetle: **Stack trace**

```
ValidationError: message mismatch: "value" must be one of [today, yesterday]
    at Object.exports.process (node_modules/joi/lib/errors.js:203:19)
    at internals.Alternatives._validateWithOptions (node_modules/joi/lib/types/any/index.js:764:31)
    at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:147:23)
    at module.exports.internals.Any.root.attempt (node_modules/joi/lib/index.js:177:29)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:52:13)
    at IcedFrisbyNock.afterJSON.json (core/service-test-runner/icedfrisby-shields.js:38:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:924:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:973:24)
    at Promise (node_modules/icedfrisby/lib/icedfrisby.js:987:7)
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:946:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1238:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

:bulb: **Possible solution**
Not sure yet. An easy fix to get the tests passing would probably be to just change the test target, but I want to dig into this a bit to determine whether we've got a bug

**Comment by calebcartwright** [comment]
I have absolutely no idea why, but the GH api is apparently showing that there are no releases for VSCode 🤔 

https://api.github.com/repos/Microsoft/vscode/releases
```json
[ ]
```

And https://api.github.com/repos/Microsoft/vscode/releases/latest is returning a 404 error

**Comment by calebcartwright** [comment]
I'm guessing at some point in the recent past there were Releases for that repo, but for whatever reason there are not anymore (at least not that I can find). I'm going to change the test target to get these passing again
