### ISSUE TITLE
Ubuntu service test failing

### ISSUE THREAD

**Issue by platan** [badges/shields#4167]
:clock11: **When did the problem start?**
2019-10-12T03_51_19_319Z or ealier

:camera: **Live badge**
https://img.shields.io/ubuntu/v/apt
![](https://img.shields.io/ubuntu/v/apt)

:wrench: **Is the live badge working?**
Yes. 

:link: **CircleCI link**

https://circleci.com/gh/badges/daily-tests/647

:beetle: **Stack trace**

```
Ubuntu [live] Ubuntu package (default distribution, valid) [ GET /apt.json ] - [ GET /apt.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" with value "v1.0.1ubuntu2.24" fails to match the required pattern: /^v(\d+:)?\d+(\.\d+)*([-+~].*)?$/
    at Object.exports.process (node_modules/@hapi/joi/lib/errors.js:183:16)
    at Object.internals.entry (node_modules/@hapi/joi/lib/validator.js:140:26)
    at Object.exports.entry (node_modules/@hapi/joi/lib/validator.js:26:30)
    at internals.Base.validate (node_modules/@hapi/joi/lib/base.js:531:26)
    at Object.internals.assert (node_modules/@hapi/joi/lib/index.js:210:27)
    at Object.attempt (node_modules/@hapi/joi/lib/index.js:100:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:61:13)
    at IcedFrisbyNock.afterJSON.json (core/service-test-runner/icedfrisby-shields.js:46:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at Promise (node_modules/icedfrisby/lib/icedfrisby.js:1017:7)
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

:bulb: **Possible solution**
- use different version validator in test
- use another package for test

**Comment by netsgnut** [comment]
Currently there are more packages that would fail the current `/^v(\d+:)?\d+(\.\d+)*([-+~].*)?$/` check.

- https://img.shields.io/ubuntu/v/ben
(`v0.8.3ubuntu4` as of writing)
- https://img.shields.io/ubuntu/v/bottlerocket
(`v0.05b3-17`)
- https://img.shields.io/ubuntu/v/brutefir
(`v1.0o-1`)
-  https://img.shields.io/ubuntu/v/openssl
(`v1.1.1b-1ubuntu2.4`)

These all would fail the current `^v(\d+:)?\d+(\.\d+)*([-+~].*)?$` check.

Given that this is actually something common, instead of changing the package performing the sanity test, probably it is better to go with changing the version validator by allowing `[-+~]` to be optional?

**Comment by calebcartwright** [comment]
Yeah I think we should update the schemas. The schema used in these service tests is much more restrictive than the actual schema used in the service class:

https://github.com/badges/shields/blob/3a6611b19930f05203c17d456e43af8ab5ee1381/services/ubuntu/ubuntu.service.js#L7-L15
