### ISSUE TITLE
Gitlab service tests failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5048]
:clock11: **When did the problem start?**
~19th April

:camera: **Live badge**

https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab-ce
![](https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab-ce)

:wrench: **Is the live badge working?**
Not sure yet, at least not with the example we have in the badge listing (which is the same target used in the service tests)

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests

:beetle: **Stack trace**

```
GitlabPipelineStatus [live] Pipeline status (branch) [ GET /gitlab-org/gitlab-ce/v10.7.6.json ] - [ GET /gitlab-org/gitlab-ce/v10.7.6.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" must be one of [fixed, passed, passing, succeeded, success, successful, partially succeeded, unstable, timeout, error, failed, failing, failure, infrastructure_failure, building, canceled, cancelled, expired, initiated, no builds, no tests, not built, not run, pending, processing, queued, running, scheduled, skipped, starting, stopped, testing, waiting]
    at Object.exports.process (node_modules/@hapi/joi/lib/errors.js:183:16)
    at Object.internals.entry (node_modules/@hapi/joi/lib/validator.js:140:26)
    at Object.exports.entry (node_modules/@hapi/joi/lib/validator.js:26:30)
    at internals.Base.validate (node_modules/@hapi/joi/lib/base.js:532:26)
    at Object.internals.assert (node_modules/@hapi/joi/lib/index.js:221:27)
    at Object.attempt (node_modules/@hapi/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.afterJSON.json (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at Promise (node_modules/icedfrisby/lib/icedfrisby.js:1017:7)
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

AssertionError: message mismatch: expected 'repo not found' to equal 'branch not found'
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:69:51)
    at IcedFrisbyNock.afterJSON.json (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at Promise (node_modules/icedfrisby/lib/icedfrisby.js:1017:7)
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

:bulb: **Possible solution**
Not sure yet

**Comment by calebcartwright** [comment]
Looks like gitlab-ce was moved to gitlab-foss, but there's no pipelines enabled on the new project.

Going to update the test and example listing targets
