### ISSUE TITLE
CLI version does not work

### ISSUE THREAD

**Issue by mdevils** [badges/shields#514]
When I run:

```
badge
```

I have the following error:
```
module.js:338
    throw err;
          ^
Error: Cannot find module './lru-cache.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Shared/Jenkins/.nvm/versions/node/v0.12.5/lib/node_modules/gh-badges/svg-to-img.js:5:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Looks like a lot of files are ignored from npm.

**Comment by espadrine** [comment]
By Jove, you are right!

Fortunately, I made it so v1.1.1 spits out SVG instead of errors!
