### ISSUE TITLE
GitLab Pipeline Status service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5282]
:clock11: **When did the problem start?**
~8 days ago, ~26th of June

:camera: **Live badge**

https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab
![](https://img.shields.io/gitlab/pipeline/gitlab-org/gitlab)

:wrench: **Is the live badge working?**
Yes

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/309/workflows/360cfa77-ba5c-422c-b2e6-dbabe6152878/jobs/1206

:beetle: **Stack trace**

```
GitlabPipelineStatus [live] Pipeline status (nonexistent repo) [ GET /this-repo/does-not-exist.json ] - [ GET /this-repo/does-not-exist.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

AssertionError: message mismatch: expected 'inaccessible' to equal 'repo not found'
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:69:51)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Not sure yet

**Comment by calebcartwright** [comment]
Spent some time looking into this one, and seems to be a pretty frustrating issue. 

We have to do svg scraping for this badge (the only GitLab badge we currently support) due to GitLab's API rate limiting and the absence of any complex workarounds (token pool). 

AFAICT, there must've been a recent change in GitLab that no longer explicitly provides a 404 response in the event of an unknown/invalid repository reference, and the user is instead redirected to a login page. The only instance I can find where we do get a 404 response is in the case that we call out in the badge builder window where a project is public but they've not checked the box to make the pipelines public.

Additionally, GitLab does support redirects for repositories that have been renamed, and it's entirely possible that we could have users of our GitLab pipeline status badge that have renamed their repository but still have the old repo name in their badge url, and the badge would still work due to the redirect.

Put more succinctly, in the case of a truly non-existent (and/or private) repository, Shields will see an HTTP 302 response and hit the GL auth page resulting in the `inaccessible` badges that's currently making the service test fail. However, Shields see's the same redirect behavior in the case of a valid/real but renamed repository. 

For example:
https://gitlab.com/this-repo/does-not-exist/badges/master/pipeline.svg (redirected to auth page)

https://gitlab.com/gitlab-org/gitlab-ce/badges/master/pipeline.svg (this repository was renamed from `gitlab-ce` to `gitlab-foss`, but the badge returns a 404 because public pipelines aren't enabled, you can see the redirect working with the project details page https://gitlab.com/gitlab-org/gitlab-ce/ --> https://gitlab.com/gitlab-org/gitlab-foss/


I see three paths forward and curious what other folks think (please also let me know if anyone has another option I've not thought of)
1. Maintain the "current" behavior; the badge message will be `inaccessible` in the event of an invalid/nonexistent repository
2. Update the service code logic to handle the upstream behavior by having to issue two requests (in the case of valid repositories); first issuing a HEAD request and if it's a 302 code and location for signin page for the specified GL instance (e.g. `https://gitlab.com/users/sign_in`) then throw a not found error, if not then issue the standard GET request for the svg
3. Basically the inverse of number 2, but optimized for the valid repo use case First issue the GET request for the svg, but have it wrapped in a try catch and do the 302/location check in the catch block to determine if the failure of the first request was due to a nonexistent repository or if the specified GL instance was actually not accessible.

I'm leaning towards option 3 at the moment even though it doesn't feel like the cleanest solution, mostly to optimize things for the majority of cases: valid repositories.
