### ISSUE TITLE
Coverity service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5518]
:clock11: **When did the problem start?**
More than 1 month ago, early August 2020

:camera: **Live badge**

https://img.shields.io/coverity/scan/3997
![](https://img.shields.io/coverity/scan/3997)

https://img.shields.io/coverity/scan/abc
![](https://img.shields.io/coverity/scan/abc)

:wrench: **Is the live badge working?**
Yes, seems to be 

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/394/workflows/d199858a-fd63-45e7-be19-392ce492fb53/jobs/1292

:beetle: **Stack trace**

```
CoverityScan [live] unknown project id [ GET /abc.json ] - [ GET /abc.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

AssertionError: message mismatch: expected 'project not found' to equal 'unparseable json response'
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:69:51)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Looks like we just need a test update as Coverity apparently started returning proper http 404 responses

**Comment by PyvesB** [comment]
> Looks like we just need a test update as Coverity apparently started returning proper http 404 responses

That's good, the error message will be much clearer for users! 👍🏻
