### ISSUE TITLE
DockerBuild Service Test Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#6107]
:clock11: **When did the problem start?**
At least ~10 days prior to the opening of this issue (~Jan 15th). It was likely failing for some time before, but was lost in the sea of the full service test failures (1900+) that we had for a while

:camera: **Live badge**
https://img.shields.io/docker/build/jrottenberg/ffmpeg

![](https://img.shields.io/docker/build/jrottenberg/ffmpeg)

:wrench: **Is the live badge working?**

Not entirely clear, though it doesn't seem like it

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/734/workflows/0288e2f4-3f93-4662-97a8-7876dbc1c757/jobs/1632

:beetle: **Stack trace**

```
DockerBuild [live] docker build status (valid, user) [ GET /jrottenberg/ffmpeg.json ] - [ GET /jrottenberg/ffmpeg.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" must be one of [fixed, passed, passing, succeeded, success, successful, partially succeeded, unstable, timeout, error, failed, failing, failure, infrastructure_failure, aborted, building, canceled, cancelled, created, expired, initiated, no builds, no tests, not built, not run, pending, processing, queued, running, scheduled, skipped, starting, stopped, testing, waiting]
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

I'm wondering if Docker have finally shut down this legacy endpoint and we'll accordingly need to deprecate this particular badge.

(more context can be found [here](https://github.com/badges/shields/issues/4716#issuecomment-592977200))

The image repository clearly still exists, and is active:
https://hub.docker.com/r/jrottenberg/ffmpeg/

and the badge which uses the "new" (several years old) endpoint is fine:
https://img.shields.io/docker/cloud/build/jrottenberg/ffmpeg
![](https://img.shields.io/docker/cloud/build/jrottenberg/ffmpeg)

This particular image has been around for a while, and definitely predates the upstream DockerHub cutover, so it almost certainly is a case of upstream deprecation.

**Comment by chris48s** [comment]
I can't see anything announcing they've removed it, but I spotted https://github.com/docker/hub-feedback/issues/2065 which I've subscribed to, in case there is any update..
