### ISSUE TITLE
Symfony Insights tests failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6187]
:clock11: **When did the problem start?**

Not 100% sure but they've been failing for at least a week

:camera: **Live badge**

All our test and example badges seem to be failing e.g:
https://img.shields.io/symfony/i/grade/45afb680-d4e6-4e66-93ea-bcfa79eb8a87

:wrench: **Is the live badge working?**

I have managed to find an example of a working badge "in the wild" e.g:
https://img.shields.io/symfony/i/grade/15c5c748-f8d8-4b56-b536-a29a151aac6c?color=success

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/773/workflows/b4870372-91f1-45a7-ad33-76d927034d16/jobs/1671/tests#failed-test-8

:beetle: **Stack trace**

```
AssertionError: label mismatch: expected 'symfony insight' to equal 'grade'
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:69:51)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:53:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

Suspect we need new example projects. I think the code/service is ok.

**Comment by calebcartwright** [comment]
https://insight.sensiolabs.com/analyses used to work as a portal for being able to browse public analysis results but it doesn't seem to anymore. Should make finding valid/working projects an interesting task going forward :laughing: 

How'd you find one that's still working? GitHub search?

**Comment by PyvesB** [comment]
We've struggled a few times with this one in the past, I remember having trouble here: https://github.com/badges/shields/pull/3933#discussion_r319767086

Gonna go ahead and fix the tests with the working example you found @chris48s ,15c5c748-f8d8-4b56-b536-a29a151aac6c
