### ISSUE TITLE
Bit Component tests failing

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6476]
:clock11: **When did the problem start?**

May 3rd 2021

:camera: **Live badge**

https://img.shields.io/bit/collection/total-components/ramda/ramda

![](https://img.shields.io/bit/collection/total-components/ramda/ramda)

:wrench: **Is the live badge working?**

No.

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/953/workflows/6839cdcb-ddf7-4803-a2c8-50542c629bff/jobs/1851/tests#failed-test-2

:beetle: **Stack trace**

```
ValidationError: message mismatch: "value" with value "inaccessible" fails to match the required pattern: /^([1-9][0-9]*[kMGTPEZY]?|[1-9]\.[1-9][kMGTPEZY])$/
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

Running the tests with trace enabled, the bit.dev API is returning a 503 error code with a HTML document which seems to be an automated browser check from Cloudfare. I'll raise an issue on the [bit](https://github.com/teambit/bit) repository.

**Comment by PyvesB** [comment]
It was apparently a firewall issue, which has now been fixed. Closing.
