### ISSUE TITLE
MyGet Downloads Test (with tenant) failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#6530]
:clock11: **When did the problem start?**
A long time ago (months)

:camera: **Live badge**

https://img.shields.io/dotnet.myget/dotnet-coreclr/v/Microsoft.DotNet.CoreCLR
![](https://img.shields.io/dotnet.myget/dotnet-coreclr/v/Microsoft.DotNet.CoreCLR)

:wrench: **Is the live badge working?**

Yes, non-"tenantized" badges are. The badges using the same target as the frontend example and service tests, are not

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/901/workflows/572b51ef-1acd-4a27-b761-c33a6352b37b/jobs/1799

:beetle: **Stack trace**

```
MyGet [live] total downloads (tenant) [ GET /dotnet.myget/dotnet-coreclr/dt/Microsoft.DotNet.CoreCLR.json ] - [ GET /dotnet.myget/dotnet-coreclr/dt/Microsoft.DotNet.CoreCLR.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" with value "intermediate resource inaccessible" fails to match the required pattern: /^([1-9][0-9]*[kMGTPEZY]?|[1-9]\.[1-9][kMGTPEZY])$/
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Not sure. I'm not familiar enough with the NuGet (much less MyGet) ecosystem to have a feel for whether this is a case of an upstream change with a test target or if something more fundamental has changed within MyGet :man_shrugging:

**Comment by calebcartwright** [comment]
Think I've found an alternative target for the tests that should work
