### ISSUE TITLE
Beerpay tests failing

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#6654]
:clock11: **When did the problem start?**

June 12th.

:camera: **Live badge**

https://img.shields.io/beerpay/hashdog/scrapfy-chrome-extension

![](https://img.shields.io/beerpay/hashdog/scrapfy-chrome-extension)

:wrench: **Is the live badge working?**

No.

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/1034/workflows/ccc55ba6-fa6a-459f-b62e-585306068c32/jobs/1932/tests#failed-test-0

:beetle: **Stack trace**

```
ValidationError: message mismatch: "value" with value "inaccessible" fails to match the required pattern: /^\$[0-9]+(\.[0-9]+)?/
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (core/service-test-runner/icedfrisby-shields.js:73:13)
    at IcedFrisbyNock.<anonymous> (core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

We should probably deprecate this service. The website is completely inaccessible at this point, and there was apparently an announcement (which can still be found here: https://web.archive.org/web/20200511170935/https://beerpay.io/goodbye) about the service going away last year, even though there wasn't any communication on their repositories or Twitter account. See https://github.com/beerpay/beerpay.io/issues/38 for more information.

**Comment by calebcartwright** [comment]
Agreed, let's deprecate it!
