### ISSUE TITLE
myget tenant service tests failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6912]
:clock11: **When did the problem start?**

~ a week ago

:camera: **Live badge**

https://img.shields.io/cefsharp.myget/cefsharp/v/cef.sdk
![](https://img.shields.io/cefsharp.myget/cefsharp/v/cef.sdk)

:wrench: **Is the live badge working?**

All the others are. I think we just need a new example for the test.

:link: **CircleCI link**

https://app.circleci.com/pipelines/github/badges/daily-tests/1158/workflows/924ad2a8-a60b-466e-8f60-36f844223da9/jobs/2059/tests

:beetle: **Stack trace**

```
AssertionError: label mismatch: expected 'myget' to equal 'cefsharp'
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:51)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:54:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

As I say, I think we just need a new example project for this test case, but I don't know how to find one. Anyone familiar with MyGet able to help?

**Comment by PyvesB** [comment]
We could simply replace `cef.sdk` with `CefSharp.Common` which we use for the downloads test. Alternatively I found the Tizen tenant/package by doing a GitHub search. Will submit a PR shortly.
