### ISSUE TITLE
Requires.io Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7015]
:clock11: **When did the problem start?**
At least 20 days ago and probably long before. I got tired of scrolling through Circle logs

:camera: **Live badge**

https://img.shields.io/requires/github/JettChenT/encryptii-server
![](https://img.shields.io/requires/github/JettChenT/encryptii-server)

:wrench: **Is the live badge working?**
Largely no for GitHub targets. The API is reporting a 404 for just about every project I've checked, with the one exception being 
https://img.shields.io/requires/github/edx/edx-platform
![](https://img.shields.io/requires/github/edx/edx-platform)

Bitbucket based targets are working

:link: **CircleCI link**
Take your pick, https://app.circleci.com/pipelines/github/badges/daily-tests/1167/workflows/e4685a3e-7aa0-4964-b238-187ad1094171/jobs/2068/tests#failed-test-4

:beetle: **Stack trace**

```
ValidationError: message mismatch: "value" with value "not found" fails to match the required pattern: /^(up to date|outdated|insecure|unknown)$/
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:74:13)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Note that at least one of the tests will definitely need to be updated, as Zulip (the target currently used by the tests) changed their default branch from `master` to `main`. However, there's something else going on upstream with the API.

I've opened an issue upstream (https://github.com/requires/api/issues/5) and pinged the person that seems to have provided the API info to us back in 2014 (refs #206). However, Requires.io doesn't seem to be an actively developed, or even regularly maintained service at least at first glance. Hopefully this will get sorted but if not we may be forced to consider a partial decom.

**Comment by PyvesB** [comment]
Looking at the [requires.io website](https://requires.io/contact/), there's a support email address listed there. I've dropped them a short message about this problem. If we don't hear back, I suggest we go ahead and deprecate these badges.

**Comment by calebcartwright** [comment]
Agreed :+1:

**Comment by PyvesB** [comment]
I've had a response. requires.io is basically in maintenance mode. They still provide native badges for their remaining users, and suggested we should go ahead and deprecate the Shields.io implementation. Will submit a pull request to that effect shortly.
