### ISSUE TITLE
Criterion service test failing and badge broken

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7134]
:clock11: **When did the problem start?**
~4 days ago

:camera: **Live badge**

https://img.shields.io/criterion/chmoder/data_vault
![](https://img.shields.io/criterion/chmoder/data_vault)

:wrench: **Is the live badge working?**

No

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1254/workflows/f8bc64b7-5813-469d-b3e3-833d5e3cec27/jobs/2155

:lady_beetle: **Stack trace**

```
Criterion [live] Criterion (not found) [ GET /chmoder/not-a-repo.json ] - [ GET /chmoder/not-a-repo.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

AssertionError: message mismatch: expected 'inaccessible' to equal 'no status found'
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:51)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Certificate has expired upstream, reported in https://github.com/chmoder/criterion.dev/issues/7. Hopefully this gets resolved in short order, otherwise the only option I can envision would be something along the lines of what we did with Jenkins a while back where we disabled strict SSL checking

**Comment by PyvesB** [comment]
This seems to have been resolved, the tests are passing and the badges display happily. I'll go ahead and close the issue.

**Comment by PyvesB** [comment]
The certificate expired again on 03/02/2022 and the badges are broken again. Reopening.

**Comment by calebcartwright** [comment]
If this doesn't get sorted within the relatively near future then I think we'll have to consider deprecating the badge. Suppose we could make modifications to allow for making an insecure request, but I'd still lean towards deprecation

**Comment by PyvesB** [comment]
Things seem to be working happily again. I'll close this issue, but let's leave the upstream one open this time around to try to get the author's attention.

**Comment by calebcartwright** [comment]
Seems to have stabilized and remained stable, closing.
