### ISSUE TITLE
SpigetDownloadSize service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7272]
:clock11: **When did the problem start?**

~6 days ago

:camera: **Live badge**
https://img.shields.io/spiget/download-size/771

![](https://img.shields.io/spiget/download-size/771)

:wrench: **Is the live badge working?**
Yes

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1320/workflows/e234f7c8-3003-4d69-8c2a-9eba6f4798e4/jobs/2222

:lady_beetle: **Stack trace**

```
AssertionError: message mismatch: expected '97.8 KB' to equal 'resource hosted externally'
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:51)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

We just need to update the test target. I don't know enough about the service nor can I recall details from when we first added support, but there's a notion of "directly" vs "externally" hosted packages, and our badge message displays something different from the latter. The failing test is occurring because the test target for the external use case has apparently been modified upstream to a direct hosting model.

**Comment by chris48s** [comment]
#7273
