### ISSUE TITLE
Drone Service Tests Failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7306]
:clock11: **When did the problem start?**
~5 days ago

:camera: **Live badge**

https://img.shields.io/drone/build/drone/drone
![](https://img.shields.io/drone/build/drone/drone)

:wrench: **Is the live badge working?**

Not really, though badges with self-hosted Drone instances may

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1334/workflows/f5af6f9a-364f-4413-91c5-ca786916d963/jobs/2236

:lady_beetle: **Stack trace**

```
ValidationError: message mismatch: "value" must be one of [fixed, passed, passing, succeeded, success, successful, partially succeeded, unstable, timeout, broken, error, errored, failed, failing, failure, infrastructure_failure, aborted, building, canceled, cancelled, created, expired, initiated, no builds, no tests, not built, not run, pending, processing, queued, running, scheduled, skipped, starting, stopped, testing, waiting, none, killed]
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:74:13)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

We're getting HTTP 401 responses on our requests, so my guess is that the main Drone Cloud instance has been updated to no longer accept anonymous requests of any kind. The API docs cover authentication, but it's unclear to me if there's any rate limiting or how widely the auth can be used (i.e. whether we can follow our common model of using a maintainer-owned token for all requests)

https://readme.drone.io/api/overview/

**Comment by PyvesB** [comment]
I tried digging into this, but couldn't create an account on the Drone Cloud instance. I left a message on the support forum here: https://community.harness.io/t/is-the-cloud-drone-io-api-still-accessible/11584

**Comment by PyvesB** [comment]
Well, turns out everything is working fine, the repository we were testing against simply moved. 🤦🏻‍♂️
