### ISSUE TITLE
GitLab Tag Nested Group service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#7321]
:clock11: **When did the problem start?**

~3 days ago

:camera: **Live badge**
https://img.shields.io/gitlab/v/tag/shields-ops-group/tag-test

![](https://img.shields.io/gitlab/v/tag/shields-ops-group/tag-test)

:wrench: **Is the live badge working?**
Yes generally, but as expected failing with the same target used for the service test.

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1361/workflows/b5f2446d-ebb5-4a91-acf1-7164857896aa/jobs/2263/tests#failed-test-2

:lady_beetle: **Stack trace**

```
ValidationError: message mismatch: "value" needs to be a valid semver expression
    at Object.exports.process (node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:74:13)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

Not sure. A local run with TRACE_SERVICES shows an apparent 404 on the target repo :man_shrugging:

**Comment by calebcartwright** [comment]
Ahh

https://gitlab.com/megabyte-labs/docker/ci-pipeline/ansible-lint

> Project 'megabyte-labs/dockerfile/ci-pipeline/ansible-lint' was moved to 'megabyte-labs/docker/ci-pipeline/ansible-lint'. Please update any links and bookmarks that may still have the old path.

GitLab's API doesn't handle forwarding/redirects on project name changes all that well as I recall so I bet that's the issue
