### ISSUE TITLE
GitLab Pipeline (nested group) service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#8069]
:clock11: **When did the problem start?**
At least a week ago

:camera: **Live badge**

https://img.shields.io/gitlab/pipeline-status/gitlab-org/gitlab?branch=master
![](https://img.shields.io/gitlab/pipeline-status/gitlab-org/gitlab?branch=master)

:wrench: **Is the live badge working?**
Yes, at least for non-nested group

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1740/workflows/66939cf5-e47e-49dc-bbcc-be10961607f6/jobs/2642/tests#failed-test-11

:lady_beetle: **Stack trace**

```Gitlab Pipeline [live] Pipeline status (nested groups) [ GET /pipeline-status/megabyte-labs/dockerfile/ci-pipeline/ansible-lint.json?branch=master ]
[ GET /pipeline-status/megabyte-labs/dockerfile/ci-pipeline/ansible-lint.json?branch=master ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" must be one of [fixed, passed, passing, succeeded, success, successful, partially succeeded, unstable, timeout, broken, error, errored, failed, failing, failure, infrastructure_failure, aborted, building, canceled, cancelled, created, expired, initiated, no builds, no tests, not built, not run, pending, processing, queued, running, scheduled, skipped, starting, stopped, testing, waiting]
    at Object.exports.process (node_modules/joi/lib/errors.js:193:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:153:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:89:13)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Potentially just needs a new test target

**Comment by sunny0826** [comment]
Can not find this project https://gitlab.com/megabyte-labs/docker/ci-pipeline/ansible-lint

https://github.com/badges/shields/blob/5e6d68123a171c9d1deb73f01ea3d1396897e1ee/services/gitlab/gitlab-pipeline-status.tester.js#L16-L23

**Comment by calebcartwright** [comment]
> Can not find this project https://gitlab.com/megabyte-labs/docker/ci-pipeline/ansible-lint

Yup, and that's what I was alluding to under the possible solution section. These live service tests can be brittle at times, or are at least highly sensitive to upstream changes. This could be a case of the project being made private, renamed, moved to a different server, etc. but regardless of what triggered it we need to either find a different project with nested groups, or rule out a more severe issue with the upstream integration (I'm reasonably confident it's the former though).

Is this something you'd be interested in working on @sunny0826?

**Comment by sunny0826** [comment]
I'm interested. Perhaps creating a **shields GitLab group** specifically for testing would be a good option.

**Comment by calebcartwright** [comment]
> I'm interested. Perhaps creating a **shields GitLab group** specifically for testing would be a good option.

Perhaps. We typically try to avoid creating Shields-owned content for tests, especially on platforms/tools we don't use (we integrate with nearly 1k of them). I did have to set up a GitLab space for us as part of proving out some tag behavior, so perhaps we could go back to that, although I've no idea how to create groups. Ideally we'd find another group out there that already works but if not I can circle back

**Comment by sunny0826** [comment]
The Pipeline badge may be special in that if it is an active project, the status of the pipeline will always be changing.

How can I help?

**Comment by calebcartwright** [comment]
> The Pipeline badge may be special in that if it is an active project, the status of the pipeline will always be changing.

That's not unique to build status badges (projects publish new versions, download counts change, etc.) and is why we don't use service tests to test for an exact value. You can see this in action in the test you linked to above where we're not testing for an explicit pass or fail, but that the message is a build status message. This allows us to test/validate the scenario (i.e. we support nested group targets) without having to worry about the precise status value.

> How can I help?

Try locating a public project that's nested in groups. Obviously if you know of any offhand that helps, but if not we'd typically do something like go search on GitLab servers.

**Comment by sunny0826** [comment]
Got it. I will fix this and #8070 in a PR.
