### ISSUE TITLE
GitLab Tag (nested group) service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#8070]
:clock11: **When did the problem start?**
At least a week ago

:camera: **Live badge**

https://img.shields.io/gitlab/v/tag/shields-ops-group/tag-test
![](https://img.shields.io/gitlab/v/tag/shields-ops-group/tag-test)

:wrench: **Is the live badge working?**
Yes, at least for non-nested group

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1740/workflows/66939cf5-e47e-49dc-bbcc-be10961607f6/jobs/2642/tests#failed-test-12

:lady_beetle: **Stack trace**

```
GitlabTag [live] Tag (nested groups) [ GET /megabyte-labs/docker/ci-pipeline/ansible-lint.json ]
[ GET /megabyte-labs/docker/ci-pipeline/ansible-lint.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

ValidationError: message mismatch: "value" needs to be a valid semver expression
    at Object.exports.process (node_modules/joi/lib/errors.js:193:16)
    at Object.internals.entry (node_modules/joi/lib/validator.js:153:26)
    at Object.exports.entry (node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (node_modules/joi/lib/index.js:225:27)
    at Object.attempt (node_modules/joi/lib/index.js:107:26)
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:89:13)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**
Potentially just needs a new test target

**Comment by sunny0826** [comment]
Similar to https://github.com/badges/shields/issues/8069#issuecomment-1153355637
