### ISSUE TITLE
OSSF Scorecard service test failing

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#8072]
:clock11: **When did the problem start?**
At least a week ago

:camera: **Live badge**

https://img.shields.io/ossf-scorecard/github.com/rohankh532/org-workflow-add
![](https://img.shields.io/ossf-scorecard/github.com/rohankh532/org-workflow-add)

:wrench: **Is the live badge working?**
Yes, for valid/enabled/scanned repositories

:link: **CircleCI link**
https://app.circleci.com/pipelines/github/badges/daily-tests/1753/workflows/9c9dd830-b535-46ca-a6ac-e8159efc4ab5/jobs/2655/tests

:lady_beetle: **Stack trace**

```
OSSFScorecard [live] score ivalid [ GET /github.com/invalid-user/invalid-repo.json ]
[ GET /github.com/invalid-user/invalid-repo.json ]
/home/circleci/project/shields/core/service-test-runner/cli.js

AssertionError: message mismatch: expected 'inaccessible' to equal 'invalid repo path'
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:85:51)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

At some point in the recent past the API started returning a 500 response code for such repositories. Have reported upstream in https://github.com/ossf/scorecard-webapp/issues/116

**Comment by calebcartwright** [comment]
This was sorted upstream (see linked issue) and the tests have been passing since, closing
