### ISSUE TITLE
joi library startup issue

### ISSUE THREAD

**Issue by MherZaqaryan** [badges/shields#8289]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Hi there, I am currently facing an issue when trying to run `npm start`.

Steps to reproduce:
1. Run `npm ci` gives me this error
```
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

added 2661 packages, and audited 2663 packages in 42s

228 packages are looking for funding
  run `npm fund` for details

51 vulnerabilities (10 moderate, 34 high, 7 critical)
```
2. Run `npm start` gives me this error
```
\shields\node_modules\joi\lib\errors.js:193
        return new exports.ValidationError(message, details, original);
               ^

Error [ValidationError]: {
  "schemaVersion": "0",
  "categories": [
    {
      "id": "build",
      "name": "Build",
      "keywords": [
        "build"
      ]
    },
    {
      "id": "coverage",
      "name": "Code Coverage",
      "keywords": [
        "coverage"
      ]
    },
    {
      "id": "test-results",
      "name": "Test Results",
      "keywords": [
        "tests"
      ]
    },
    {
      "id": "analysis",
      "name": "Analysis",
      "keywords": [
        "analysis"
      ]
    },
    {
      "id": "chat",
      "name": "Chat",
      "keywords": [
        "chat"
      ]
    },
    {
      "id": "dependencies",
      "name": "Dependencies",
      "keywords": [
        "dependencies"
      ]
    },
    {
      "id": "size",
      "name": "Size",
      "keywords": [
        "size"
      ]
    },
    {
      "id": "downloads",
      "name": "Downloads",
      "keywords": [
        "downloads"
      ]
    },
    {
      "id": "funding",
      "name": "Funding",
      "keywords": [
        "funding"
      ]
    },
    {
      "id": "issue-tracking",
      "name": "Issue Tracking",
      "keywords": [
        "issue"
      ]
    },
    {
      "id": "license",
      "name": "License",
      "keywords": [
        "license"
      ]
    },
    {
      "id": "rating",
      "name": "Rating",
      "keywords": [
        "rating"
      ]
    },
    {
      "id": "social",
      "name": "Social",
      "keywords": [
        "social"
      ]
    },
    {
      "id": "version",
      "name": "Version",
      "keywords": [
        "version"
      ]
    },
    {
      "id": "platform-support",
      "name": "Platform & Version Support",
      "keywords": [
        "platform"
      ]
    },
    {
      "id": "monitoring",
      "name": "Monitoring",
      "keywords": [
        "monitoring"
      ]
    },
    {
      "id": "activity",
      "name": "Activity",
      "keywords": [
        "activity"
      ]
    },
    {
      "id": "other",
      "name": "Other",
      "keywords": []
    }
  ],
  "services" [1]: []
}

[1] "services" does not contain 1 required value(s)
    at Object.exports.process (shields\node_modules\joi\lib\errors.js:193:16)
    at Object.internals.entry (shields\node_modules\joi\lib\validator.js:153:26)        
    at Object.exports.entry (shields\node_modules\joi\lib\validator.js:27:30)
    at internals.Base.validate (shields\node_modules\joi\lib\base.js:548:26)
    at Object.internals.assert (shields\node_modules\joi\lib\index.js:225:27)
    at Object.assert (shields\node_modules\joi\lib\index.js:102:19)
    at assertValidServiceDefinitionExport (shields/core/base-service/service-definitions.js:70:7)
    at collectDefinitions (shields/core/base-service/loader.js:89:3)
    at async shields/scripts/export-service-definitions-cli.js:4:23 {
  _original: {
    schemaVersion: '0',
    categories: [
      { id: 'build', name: 'Build', keywords: [ 'build' ] },
      {
        id: 'coverage',
        name: 'Code Coverage',
        keywords: [ 'coverage' ]
      },
      {
        id: 'test-results',
        name: 'Test Results',
        keywords: [ 'tests' ]
      },
      { id: 'analysis', name: 'Analysis', keywords: [ 'analysis' ] },
      { id: 'chat', name: 'Chat', keywords: [ 'chat' ] },
      {
        id: 'dependencies',
        name: 'Dependencies',
        keywords: [ 'dependencies' ]
      },
      { id: 'size', name: 'Size', keywords: [ 'size' ] },
      { id: 'downloads', name: 'Downloads', keywords: [ 'downloads' ] },
      { id: 'funding', name: 'Funding', keywords: [ 'funding' ] },
      {
        id: 'issue-tracking',
        name: 'Issue Tracking',
        keywords: [ 'issue' ]
      },
      { id: 'license', name: 'License', keywords: [ 'license' ] },
      { id: 'rating', name: 'Rating', keywords: [ 'rating' ] },
      { id: 'social', name: 'Social', keywords: [ 'social' ] },
      { id: 'version', name: 'Version', keywords: [ 'version' ] },
      {
        id: 'platform-support',
        name: 'Platform & Version Support',
        keywords: [ 'platform' ]
      },
      {
        id: 'monitoring',
        name: 'Monitoring',
        keywords: [ 'monitoring' ]
      },
      { id: 'activity', name: 'Activity', keywords: [ 'activity' ] },
      { id: 'other', name: 'Other', keywords: [] }
    ],
    services: []
  },
  details: [
    {
      message: '"services" does not contain 1 required value(s)',
      path: [ 'services' ],
      type: 'array.includesRequiredUnknowns',
      context: {
        unknownMisses: 1,
        label: 'services',
        value: [],
        key: 'services'
      }
    }
  ]
}
```

So basically, I am not able to run the development server on my machine. There is this `joi` library that probably causes the issue.

Environment Information:
OS: Windows 11 Pro
NodeJS Version: v16.16.0
NPM Version: v8.11.0

**Comment by chris48s** [comment]
I don't have a solution for this off the top of my head, but basically the issue here is that the service definitions are being generated with no examples for any category and the validation is failing here

https://github.com/badges/shields/blob/547e2b8bd4b6b28ca873df7c1218c15ca454d242/core/base-service/service-definitions.js#L55-L71

I'm pretty sure someone else has hit the same error on Windows and I'd be quite keen to accept a fix for this as there's no good reason why this codebase can't run on Windows. In general, we try to keep things cross-platform compatible (e.g: rimraf, cross-env, etc) Its just that none of the core team use Windows so these kind of issues can slip the net.

Fundamentally, the code path for generating the service definitions when we run `npm start` is:

- https://github.com/badges/shields/blob/547e2b8bd4b6b28ca873df7c1218c15ca454d242/package.json#L114
- https://github.com/badges/shields/blob/547e2b8bd4b6b28ca873df7c1218c15ca454d242/package.json#L104
- https://github.com/badges/shields/blob/master/scripts/export-service-definitions-cli.js
- https://github.com/badges/shields/blob/master/core/base-service/loader.js

so probably the issue is somewhere in that, but superficially it looks like we're making a pretty good job of using cross-platform calls in loader.js (e.g: `path.join`, `path.sep`, etc)

**Comment by calebcartwright** [comment]
It has worked on Windows in the not-too-distant past, so I suspect an issue that was triggered either as part of a dependency update or perhaps an update of Node itself.

We could also consider adding a CI check that runs on Windows (can use GHA if Circle doesn't support Windows)

**Comment by bastijnv** [comment]
The issue is in [loader.js](https://github.com/badges/shields/blob/master/core/base-service/loader.js). 
line 25 will not work for a windows path, which is what is returned by the output of path.join (and the servicePath before). You can easily fix this by adding a replace:

`
  servicePaths = glob.sync(path.join(serviceDir, '**', '*.service.js').replace(/\\/g, '/')) `

**Comment by calebcartwright** [comment]
Great find @bastijnv! By any chance would you be interested in submitting a PR with the fix? :pray:

**Comment by bastijnv** [comment]
@calebcartwright I can when I have some time. Not sure if that will be this weekend. Can probably raise a PR next Monday.

**Comment by chris48s** [comment]
I've started a PR at https://github.com/badges/shields/pull/8350 to try and get a build passing on windows. @bastijnv 's suggestion gets us part of the way there but there is still at least one more issue to work out.
