### ISSUE TITLE
Error running `test:services:trace`,  "Cannot find any files matching pattern "$*"" on Windows

### ISSUE THREAD

**Issue by alexandresanlim** [badges/shields#8437]
:clock11: **When did the problem start?**

When start [this sample](https://github.com/badges/shields/blob/master/doc/service-tests.md#3-running-the-tests) to run my first test

:lady_beetle: **Stack trace**

```
<!-- Provide the complete stack trace from the CircleCI test summary. -->

PS C:\Workspace\shieldsale\shields> npm run test:services:trace -- --only=wercker

> shields.io@0.0.0 test:services:trace
> cross-env NODE_CONFIG_ENV=test TRACE_SERVICES=true npm run test:services -- $*


> shields.io@0.0.0 test:services
> cross-env NODE_CONFIG_ENV=test mocha core/service-test-runner/cli.js

Warning: Cannot find any files matching pattern "$*"
Running tests for 1 services: wercker.


Error: Unknown services: wercker
    at Runner.only (file:///C:/Workspace/shieldsale/shields/core/service-test-runner/runner.js:64:13)
    at file:///C:/Workspace/shieldsale/shields/core/service-test-runner/cli.js:127:10

```

**Comment by calebcartwright** [comment]
The output from this is just.. odd. Can you please confirm you are working a local copy of this repository (as opposed to a fork) and share which commit you are on?

**Comment by alexandresanlim** [comment]
I'm working on this fork:
https://github.com/alexandresanlim/shields

**Comment by chris48s** [comment]
If you just run `npm run test:services -- --only="wercker"`, does that work?

**Comment by alexandresanlim** [comment]
> If you just run `npm run test:services -- --only="wercker"`, does that work?

Yes, I just ran this command according to the first line

**Comment by chris48s** [comment]
OK. Thanks I guess the issue is that the `$*` in

https://github.com/badges/shields/blob/7330da1038904c0be5b21c80ca440bebc07335ed/package.json#L93

doesn't work on Windows. Not sure how we work round that in a cross-platform way.

**Comment by alexandresanlim** [comment]
@chris48s I have new changes to open a PR, can i open it without tests or waiting fix?

**Comment by chris48s** [comment]
If you just want to run the tests for your new service, you can do it with `npm run test:services -- only="your-service-name"`.

`npm run test:services:trace` is useful for debugging failing tests, but you should be able to submit a working PR without this issue being fixed.

**Comment by alexandresanlim** [comment]
`npm run test:services -- only="wercker"` results in:
```
> shields.io@0.0.0 test:services
> cross-env NODE_CONFIG_ENV=test mocha core/service-test-runner/cli.js

Warning: Cannot find any files matching pattern "only=wercker"
Running all service tests.
(node:28572) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)


  0 passing (0ms)

PS C:\Workspace\shieldsale\shields>
``` 

and` npm run test:services -- --only=wercker `results in:

```
> shields.io@0.0.0 test:services
> cross-env NODE_CONFIG_ENV=test mocha core/service-test-runner/cli.js

Running tests for 1 services: wercker.

Error: Unknown services: wercker
    at Runner.only (file:///C:/Workspace/shieldsale/shields/core/service-test-runner/runner.js:64:13)
    at file:///C:/Workspace/shieldsale/shields/core/service-test-runner/cli.js:127:10
PS C:\Workspace\shieldsale\shields> 
```

**Comment by confused-Techie** [comment]
Also on Windows, and also unable to run the test suite.

I tried a few different ways, which I'll detail below as well as the output received.

Windows: 22H2
Node: v16.16.0

Command:
```
npm run test:services
```

Output:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> shields.io@0.0.0 test:services
> cross-env NODE_CONFIG_ENV=test mocha core/service-test-runner/cli.js

Running all service tests.
(node:34612) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

  0 passing (0ms)
```

Command:
```
npm run test:services -- --only="pub"
```

Output:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> shields.io@0.0.0 test:services
> cross-env NODE_CONFIG_ENV=test mocha core/service-test-runner/cli.js "--only=pub"

Running tests for 1 services: pub.


Error: Unknown services: pub
    at Runner.only (file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/runner.js:64:13)
    at file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/cli.js:127:10
```

Command:
```
npm run test:services:trace -- --only="pub"
```

Output:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> shields.io@0.0.0 test:services:trace
> cross-env NODE_CONFIG_ENV=test TRACE_SERVICES=true npm run test:services -- $* "--only=pub"

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> shields.io@0.0.0 test:services

Warning: Cannot find any files matching pattern "$*"
Running tests for 1 services: pub.


Error: Unknown services: pub
    at Runner.only (file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/runner.js:64:13)
    at file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/cli.js:127:10
```

Command:
```
npx mocha core/service-test-runner/cli.js --only="wercker"
```

Output:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Running tests for 1 services: wercker.


Error: Unknown services: wercker
    at Runner.only (file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/runner.js:64:    at file:///D:/Personal%20Documents/GitHub%20Repositories/shields/core/service-test-runner/cli.js:127:10
```

**Comment by chris48s** [comment]
We've now merged https://github.com/badges/shields/pull/8786 which should allow you to run the basic tests for a service (without `:trace`) e.g: `npm run test:services -- --only="pub"` (or whatever) natively on Windows
